### ISSUE TITLE
Update to Polymer 1.7

### ISSUE THREAD

**Issue by LasaleFamine** [LasaleFamine/ace-editor#6]
[New Polymer 1.7](https://www.polymer-project.org/1.0/blog/2016-10-03-1.7-release)

Check if we are using `<content>` elements and replace with `<slot>`.

**Comment by dhruvdutt** [comment]
#7 
We aren't using `<content>` anywhere in our project.
Also please add `hacktoberfest` label to the PR.

**Comment by LasaleFamine** [comment]
Merged #8.

Thank you again.
